name: Deploy Express App to Azure

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm ci

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'poultrypro-backend'
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE_BACKEND }}
          package: .

      - name: Setup Application Insights
        run: |
          npm install applicationinsights
          echo "const appInsights = require('applicationinsights'); appInsights.setup().start();" >> src/index.js

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Check Autoscale Settings
        run: |
          autoscale_settings=$(az monitor autoscale show --resource-group PoultryProRG --name autoscale-poultrypro)
          echo "Current Autoscale Configuration:"
          echo $autoscale_settings | jq .

      - name: Check App Service Plan
        run: |
          az appservice plan show --name PoultryProPlan --resource-group PoultryProRG --query "{sku:sku.name, capacity:sku.capacity}"
