name: Deploy Express App to Azure

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm ci

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'poultrypro-backend'
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE_BACKEND }}
          package: .

      - name: Setup Application Insights
        run: |
          npm install applicationinsights
          echo "const appInsights = require('applicationinsights'); appInsights.setup().start();" >> src/index.js

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Set Web App Settings
        uses: azure/appservice-settings@v1
        with:
          app-name: 'poultrypro-backend'
          app-settings-json: |
            [
              {
                "name": "FIREBASE_API_KEY",
                "value": "${{ secrets.FIREBASE_API_KEY }}"
              },
              {
                "name": "FIREBASE_DATABASE_URL",
                "value": "${{ secrets.FIREBASE_DATABASE_URL }}"
              },
              {
                "name": "FIREBASE_PROJECT_ID",
                "value": "${{ secrets.FIREBASE_PROJECT_ID }}"
              },
              {
                "name": "FIREBASE_STORAGE_BUCKET",
                "value": "${{ secrets.FIREBASE_STORAGE_BUCKET }}"
              },
              {
                "name": "FIREBASE_MESSAGING_SENDER_ID",
                "value": "${{ secrets.FIREBASE_MESSAGING_SENDER_ID }}"
              },
              {
                "name": "FIREBASE_APP_ID",
                "value": "${{ secrets.FIREBASE_APP_ID }}"
              },
              {
                "name": "APPLICATIONINSIGHTS_CONNECTION_STRING",
                "value": "${{ secrets.APPINSIGHTS_CONNECTION_STRING }}"
              },
              {
                "name": "FIREBASE_TYPE",
                "value": "${{ secrets.FIREBASE_TYPE }}"
              },
              {
                "name": "FIREBASE_PRIVATE_KEY",
                "value": "${{ secrets.FIREBASE_PRIVATE_KEY }}"
              },
              {
                "name": "FIREBASE_PRIVATE_KEY_ID",
                "value": "${{ secrets.FIREBASE_PRIVATE_KEY_ID }}"
              },
              {
                "name": "FIREBASE_CLIENT_EMAIL",
                "value": "${{ secrets.FIREBASE_CLIENT_EMAIL }}"
              },
              {
                "name": "FIREBASE_CLIENT_ID",
                "value": "${{ secrets.FIREBASE_CLIENT_ID }}"
              },
              {
                "name": "FIREBASE_AUTH_URI",
                "value": "${{ secrets.FIREBASE_AUTH_URI }}"
              },
              {
                "name": "FIREBASE_TOKEN_URI",
                "value": "${{ secrets.FIREBASE_TOKEN_URI }}"
              },
              {
                "name": "FIREBASE_AUTH_PROVIDER_X509_CERT_URL",
                "value": "${{ secrets.FIREBASE_AUTH_PROVIDER_X509_CERT_URL }}"
              },
              {
                "name": "FIREBASE_CLIENT_X509_CERT_URL",
                "value": "${{ secrets.FIREBASE_CLIENT_X509_CERT_URL }}"
              },
              {
                "name": "FIREBASE_UNIVERSE_DOMAIN",
                "value": "${{ secrets.FIREBASE_UNIVERSE_DOMAIN }}"
              }
            ]

      - name: Check Autoscale Settings
        run: |
          autoscale_settings=$(az monitor autoscale show --resource-group PoultryProRG --name autoscale-poultrypro)
          echo "Current Autoscale Configuration:"
          echo $autoscale_settings | jq .

      - name: Check App Service Plan
        run: |
          az appservice plan show --name PoultryProPlan --resource-group PoultryProRG --query "{sku:sku.name, capacity:sku.capacity}"
